import React,{useCallback,useEffect,useState}from'react';
import{ActivityIndicator,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useRouter}from'expo-router';
import{BRAND}from'@/lib/brand';
import{AdminCommunityGrower,AdminCommunityListing,getAdminCommunityGrowers,getAdminCommunityListings,setAdminCommunityGrowerStatus,setAdminCommunityListingStatus}from'@/services/adminCommunityService';

export default function AdminCommunity(){
 const router=useRouter();const[g,setG]=useState<AdminCommunityGrower[]>([]);const[l,setL]=useState<AdminCommunityListing[]>([]);const[loading,setLoading]=useState(true);const[action,setAction]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([getAdminCommunityGrowers(),getAdminCommunityListings()]);setG(a);setL(b);}catch(e:any){alert(e?.message||'Could not load community marketplace.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const grower=async(x:AdminCommunityGrower,status:'active'|'rejected')=>{if(typeof window!=='undefined'&&!window.confirm(status==='active'?'Approve this community grower?':'Reject this grower?'))return;setAction(x.id);try{await setAdminCommunityGrowerStatus(x.id,status);await load()}catch(e:any){alert(e?.message||'Could not update grower.')}finally{setAction('')}};
 const listing=async(x:AdminCommunityListing,status:'approved'|'rejected')=>{if(typeof window!=='undefined'&&!window.confirm(status==='approved'?'Approve this listing for customers?':'Reject this listing?'))return;setAction(x.id);try{await setAdminCommunityListingStatus(x.id,status);await load()}catch(e:any){alert(e?.message||'Could not update listing.')}finally{setAction('')}};
 if(loading)return <SafeAreaView style={s.loading}><ActivityIndicator size="large" color={BRAND.teal}/><Text style={s.muted}>Loading community marketplace...</Text></SafeAreaView>;
 return <SafeAreaView style={s.c}><ScrollView refreshControl={<RefreshControl refreshing={false} onRefresh={load}/>} contentContainerStyle={s.content}>
 <TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹ BACK</Text></TouchableOpacity>
 <Text style={s.eye}>GARDENVERSE OPERATIONS</Text><Text style={s.title}>Grower & Listing Control</Text><Text style={s.sub}>Approve residents and the products they grow before customers can buy them.</Text>
 <View style={s.stats}><View style={s.stat}><Text style={s.num}>{g.length}</Text><Text style={s.lab}>GROWERS</Text></View><View style={s.stat}><Text style={s.num}>{g.filter(x=>x.status==='pending').length}</Text><Text style={s.lab}>GROWER REVIEW</Text></View><View style={s.stat}><Text style={s.num}>{l.filter(x=>x.status==='pending').length}</Text><Text style={s.lab}>LISTING REVIEW</Text></View></View>
 <Text style={s.section}>RESIDENT GROWERS</Text>{g.length===0?<Text style={s.empty}>No community growers yet.</Text>:g.map(x=><View style={s.card} key={x.id}><Text style={s.name}>👩‍🌾 {x.display_name}</Text><Text style={s.meta}>{x.locality||'Kolkata'} · {x.space_type} · {x.listing_count} listings</Text><Text style={s.status}>{x.status.toUpperCase()}</Text>{x.status==='pending'&&<View style={s.actions}><TouchableOpacity style={s.approve} disabled={!!action} onPress={()=>grower(x,'active')}><Text style={s.white}>APPROVE</Text></TouchableOpacity><TouchableOpacity style={s.reject} disabled={!!action} onPress={()=>grower(x,'rejected')}><Text style={s.red}>REJECT</Text></TouchableOpacity></View>}</View>)}
 <Text style={s.section}>PRODUCT LISTINGS</Text>{l.length===0?<Text style={s.empty}>No community listings yet.</Text>:l.map(x=><View style={s.card} key={x.id}><Text style={s.name}>{x.emoji} {x.title}</Text><Text style={s.meta}>👩‍🌾 {x.grower_display_name}{x.locality?' · '+x.locality:''}</Text><Text style={s.meta}>₹{Number(x.price).toLocaleString('en-IN')} / {x.unit} · {x.quantity_available} available</Text><Text style={s.status}>{x.status.toUpperCase()}</Text>{x.status==='pending'&&<View style={s.actions}><TouchableOpacity style={s.approve} disabled={!!action} onPress={()=>listing(x,'approved')}><Text style={s.white}>APPROVE LISTING</Text></TouchableOpacity><TouchableOpacity style={s.reject} disabled={!!action} onPress={()=>listing(x,'rejected')}><Text style={s.red}>REJECT</Text></TouchableOpacity></View>}</View>)}
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:BRAND.cream},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:BRAND.cream},muted:{marginTop:10,color:BRAND.muted},content:{padding:20,paddingBottom:60},back:{color:BRAND.teal,fontWeight:'900',marginBottom:25},eye:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:BRAND.teal},title:{fontSize:28,fontWeight:'900',color:BRAND.midnight,marginTop:5},sub:{fontSize:12,lineHeight:18,color:BRAND.muted,marginTop:6,marginBottom:20},stats:{flexDirection:'row',gap:8,marginBottom:25},stat:{flex:1,backgroundColor:'#FFF',borderRadius:16,padding:13},num:{fontSize:20,fontWeight:'900',color:BRAND.midnight},lab:{fontSize:7,fontWeight:'900',color:BRAND.muted,marginTop:3},section:{fontSize:12,fontWeight:'900',letterSpacing:1,color:BRAND.midnight,marginTop:8,marginBottom:10},card:{backgroundColor:'#FFF',borderRadius:18,padding:15,marginBottom:10},name:{fontSize:15,fontWeight:'900',color:BRAND.midnight},meta:{fontSize:10,color:'#477057',fontWeight:'800',marginTop:4},status:{alignSelf:'flex-start',marginTop:8,paddingHorizontal:8,paddingVertical:4,borderRadius:8,backgroundColor:'#EEF2F5',fontSize:8,fontWeight:'900'},actions:{flexDirection:'row',gap:8,marginTop:12},approve:{flex:1,padding:11,borderRadius:11,backgroundColor:BRAND.midnight,alignItems:'center'},white:{color:'#FFF',fontSize:9,fontWeight:'900'},reject:{flex:1,padding:11,borderRadius:11,backgroundColor:'#FDECEC',alignItems:'center'},red:{color:'#A43D3D',fontSize:9,fontWeight:'900'},empty:{color:BRAND.muted,padding:10}});
