import React,{useCallback,useEffect,useState}from'react';
import{RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useRouter}from'expo-router';
import{BRAND}from'@/lib/brand';
import{getAdminHomeKitchens,getAdminHomeKitchenItems,setAdminHomeKitchenStatus,setAdminHomeKitchenItemStatus,AdminKitchen,AdminKitchenItem}from'@/services/adminHomeKitchenService';

export default function AdminHomeKitchens(){
 const router=useRouter();const[k,setK]=useState<AdminKitchen[]>([]);const[i,setI]=useState<AdminKitchenItem[]>([]);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([getAdminHomeKitchens(),getAdminHomeKitchenItems()]);setK(a);setI(b)}catch(e:any){alert(e?.message||'Could not load Home Kitchens')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const approve=async(x:AdminKitchen)=>{if(typeof window!=='undefined'&&!window.confirm('Approve this kitchen? Only do this after required food-business verification.'))return;try{await setAdminHomeKitchenStatus(x.id,'approved','verified','verified');await load()}catch(e:any){alert(e?.message||'Could not approve kitchen')}};
 const reject=async(x:AdminKitchen)=>{if(typeof window!=='undefined'&&!window.confirm('Reject this kitchen?'))return;try{await setAdminHomeKitchenStatus(x.id,'rejected',x.fssai_status,x.hygiene_status);await load()}catch(e:any){alert(e?.message||'Could not reject kitchen')}};
 const approveItem=async(x:AdminKitchenItem)=>{if(typeof window!=='undefined'&&!window.confirm('Approve this menu item?'))return;try{await setAdminHomeKitchenItemStatus(x.id,'approved');await load()}catch(e:any){alert(e?.message||'Could not approve item')}};
 return <SafeAreaView style={s.c}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.content}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹ BACK</Text></TouchableOpacity><Text style={s.eye}>COMMUNITY COMMERCE</Text><Text style={s.title}>Home Kitchen Control</Text><Text style={s.sub}>Verify kitchens and menu items before customers can order.</Text><View style={s.stats}><View style={s.stat}><Text style={s.num}>{k.length}</Text><Text style={s.lab}>KITCHENS</Text></View><View style={s.stat}><Text style={s.num}>{k.filter(x=>x.status==='pending').length}</Text><Text style={s.lab}>KITCHEN REVIEW</Text></View><View style={s.stat}><Text style={s.num}>{i.filter(x=>x.status==='pending').length}</Text><Text style={s.lab}>MENU REVIEW</Text></View></View><Text style={s.section}>KITCHENS</Text>{k.length===0?<Text style={s.empty}>No Home Kitchen applications.</Text>:k.map(x=><View style={s.card} key={x.id}><Text style={s.name}>👩‍🍳 {x.kitchen_name}</Text><Text style={s.meta}>{x.display_name} · {x.locality||'Kolkata'} · {x.item_count} menu items</Text><Text style={s.meta}>{x.women_led?'Women-led · ':''}FSSAI: {x.fssai_status}{x.fssai_number?' · '+x.fssai_number:''} · Hygiene: {x.hygiene_status}</Text><Text style={s.status}>{x.status.toUpperCase()}</Text>{x.status==='pending'?<View style={s.actions}><TouchableOpacity style={s.approve} onPress={()=>approve(x)}><Text style={s.white}>VERIFY & APPROVE</Text></TouchableOpacity><TouchableOpacity style={s.reject} onPress={()=>reject(x)}><Text style={s.red}>REJECT</Text></TouchableOpacity></View>:null}</View>)}<Text style={s.section}>MENU ITEMS</Text>{i.length===0?<Text style={s.empty}>No menu items awaiting review.</Text>:i.map(x=><View style={s.card} key={x.id}><Text style={s.name}>{x.emoji} {x.title}</Text><Text style={s.meta}>{x.kitchen_name} · ₹{Number(x.price).toLocaleString('en-IN')} / {x.unit} · {x.quantity_available} available</Text><Text style={s.status}>{x.status.toUpperCase()}</Text>{x.status==='pending'?<TouchableOpacity style={s.approve} onPress={()=>approveItem(x)}><Text style={s.white}>APPROVE MENU ITEM</Text></TouchableOpacity>:null}</View>)}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:BRAND.cream},content:{padding:20,paddingBottom:60},back:{color:BRAND.teal,fontWeight:'900',marginBottom:25},eye:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:BRAND.teal},title:{fontSize:28,fontWeight:'900',color:BRAND.midnight,marginTop:5},sub:{fontSize:12,lineHeight:18,color:BRAND.muted,marginTop:6,marginBottom:20},stats:{flexDirection:'row',gap:8,marginBottom:22},stat:{flex:1,backgroundColor:'#FFF',borderRadius:16,padding:13},num:{fontSize:20,fontWeight:'900',color:BRAND.midnight},lab:{fontSize:7,fontWeight:'900',color:BRAND.muted,marginTop:3},section:{fontSize:12,fontWeight:'900',letterSpacing:1,color:BRAND.midnight,marginTop:8,marginBottom:10},card:{backgroundColor:'#FFF',borderRadius:18,padding:15,marginBottom:10},name:{fontSize:15,fontWeight:'900',color:BRAND.midnight},meta:{fontSize:10,color:'#477057',fontWeight:'800',marginTop:4},status:{alignSelf:'flex-start',marginTop:8,paddingHorizontal:8,paddingVertical:4,borderRadius:8,backgroundColor:'#EEF2F5',fontSize:8,fontWeight:'900'},actions:{flexDirection:'row',gap:8,marginTop:10},approve:{flex:1,padding:11,borderRadius:11,backgroundColor:BRAND.midnight,alignItems:'center'},white:{color:'#FFF',fontSize:9,fontWeight:'900'},reject:{flex:1,padding:11,borderRadius:11,backgroundColor:'#FDECEC',alignItems:'center'},red:{color:'#A43D3D',fontSize:9,fontWeight:'900'},empty:{color:BRAND.muted,padding:10}});
