import { BRAND } from '@/lib/brand';
import { supabase } from '@/lib/supabase';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useState } from 'react';
import * as Location from 'expo-location';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

type Listing = { id:string; title:string; emoji:string; category:string; unit:string; price:number; quantity_available:number; grower_display_name:string; locality:string|null; notes:string|null; };
const fee = (subtotal:number) => subtotal >= 499 ? 0 : subtotal >= 299 ? 29 : 49;
const makeOrderId = () => 'CI-' + new Date().getFullYear() + '-' + String(Date.now()).slice(-8) + String(Math.floor(Math.random()*90+10));

export default function CommunityCheckoutScreen() {
  const router = useRouter();
  const { listingId } = useLocalSearchParams<{ listingId?: string }>();
  const [listing,setListing]=useState<Listing|null>(null); const [quantity,setQuantity]=useState('1');
  const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [address,setAddress]=useState(''); const [area,setArea]=useState(''); const [pin,setPin]=useState('');
  const [locating,setLocating]=useState(false); const [saving,setSaving]=useState(false); const [orderError,setOrderError]=useState(''); const [deliveryLocation,setDeliveryLocation]=useState<{latitude:number;longitude:number;accuracy:number|null} | null>(null);
  useEffect(()=>{ (async()=>{ if(!listingId) return; const {data,error}=await supabase.from('chalega_grower_listings').select('id,title,emoji,category,unit,price,quantity_available,grower_display_name,locality,notes').eq('id',listingId).eq('status','approved').gt('quantity_available',0).maybeSingle(); if(error||!data){Alert.alert('Community Market','This listing is no longer available.'); router.back(); return;} setListing(data as Listing); })(); },[listingId]);
  const qty=Math.max(1,Math.min(100,Number.parseInt(quantity,10)||1)); const subtotal=listing ? Number(listing.price)*qty : 0; const delivery=fee(subtotal); const total=subtotal+delivery;
  const pinLocation=async()=>{try{setLocating(true);const p=await Location.requestForegroundPermissionsAsync();if(!p.granted)throw new Error('Location permission is required.');const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High,mayShowUserSettingsDialog:true});setDeliveryLocation({latitude:current.coords.latitude,longitude:current.coords.longitude,accuracy:current.coords.accuracy||null});Alert.alert('Location pinned','GPS captured (±'+Math.round(current.coords.accuracy||0)+'m).');}catch(e:any){Alert.alert('Could not get location',e?.message||'Please enable Location Services.');}finally{setLocating(false);}};
  const placeOrder=async()=>{setOrderError('');if(!listing)return;if(!name.trim()||!phone.trim()||!address.trim()){setOrderError('Name, phone and address are required.');return;}if(qty>listing.quantity_available){setOrderError('Only '+listing.quantity_available+' are available.');return;}setSaving(true);try{const {data,error}=await supabase.rpc('create_chalega_community_order',{p_order_id:makeOrderId(),p_listing_id:listing.id,p_quantity:qty,p_customer_name:name.trim(),p_customer_phone:phone.trim(),p_address:address.trim(),p_area:area.trim(),p_pin:pin.trim(),p_latitude:deliveryLocation?.latitude ?? null,p_longitude:deliveryLocation?.longitude ?? null});if(error||!data?.[0]){setOrderError(error?.message||'The order could not be placed. Please try again.');return;}const o=data[0];router.replace({pathname:'/order-confirmed',params:{orderId:o.order_id,name:name.trim(),total:String(o.total),deliveryDeadline:o.delivery_deadline}});}catch(e:any){setOrderError(e?.message||'The order could not be placed. Please try again.');}finally{setSaving(false);}};
  if(!listing)return <SafeAreaView style={styles.container}><View style={styles.empty}><Text style={styles.title}>Loading community listing...</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.hero}><TouchableOpacity style={styles.back} onPress={()=>router.back()}><Text style={styles.backText}>‹</Text></TouchableOpacity><Text style={styles.eyebrow}>CHALIGA GARDENVERSE</Text><Text style={styles.title}>COMMUNITY CHECKOUT</Text><Text style={styles.subtitle}>Buy directly from a Kolkata community grower.</Text></View>
    <View style={styles.product}><Text style={styles.emoji}>{listing.emoji}</Text><View style={styles.productBody}><Text style={styles.name}>{listing.title}</Text><Text style={styles.meta}>👩‍🌾 {listing.grower_display_name}{listing.locality ? ' · '+listing.locality : ''}</Text><Text style={styles.price}>₹{Number(listing.price).toLocaleString('en-IN')} / {listing.unit}</Text><Text style={styles.stock}>{listing.quantity_available} available</Text></View></View>
    <View style={styles.card}><Text style={styles.section}>QUANTITY</Text><TextInput value={quantity} onChangeText={setQuantity} keyboardType='number-pad' style={styles.input}/><Text style={styles.section}>DELIVERY DETAILS</Text><TextInput value={name} onChangeText={setName} placeholder='Full name' placeholderTextColor='#8794A0' style={styles.input}/><TextInput value={phone} onChangeText={setPhone} placeholder='Phone number' placeholderTextColor='#8794A0' keyboardType='phone-pad' style={styles.input}/><TextInput value={address} onChangeText={setAddress} placeholder='Full delivery address' placeholderTextColor='#8794A0' style={[styles.input,styles.area]} multiline/><TextInput value={area} onChangeText={setArea} placeholder='Area / locality' placeholderTextColor='#8794A0' style={styles.input}/><TextInput value={pin} onChangeText={setPin} placeholder='PIN code' placeholderTextColor='#8794A0' keyboardType='number-pad' style={styles.input}/><TouchableOpacity style={styles.location} onPress={pinLocation} disabled={locating}><Text style={styles.locationText}>{locating?'PINNING GPS...':deliveryLocation?'✓ GPS LOCATION PINNED':'📍 PIN MY CURRENT LOCATION'}</Text></TouchableOpacity></View>
    <View style={styles.summary}><Text style={styles.summaryTitle}>ORDER SUMMARY</Text><View style={styles.row}><Text>Plants</Text><Text>₹{subtotal.toLocaleString('en-IN')}</Text></View><View style={styles.row}><Text>Chaliga delivery</Text><Text>{delivery===0?'FREE':'₹'+delivery}</Text></View><View style={styles.total}><Text>TOTAL · COD</Text><Text>₹{total.toLocaleString('en-IN')}</Text></View></View>
    {orderError ? <View style={styles.error}><Text style={styles.errorText}>{orderError}</Text></View> : null}
    <Pressable style={({pressed})=>[styles.place,pressed&&styles.placePressed]} onPress={()=>{void placeOrder();}} disabled={saving}><Text style={styles.placeText}>{saving?'PLACING ORDER...':'PLACE COMMUNITY ORDER · COD'}</Text></Pressable>
    <Text style={styles.note}>CHALIGA coordinates delivery. The grower receives an earnings record for the sale and is paid through the community settlement process.</Text>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:BRAND.cream},content:{paddingBottom:60},hero:{backgroundColor:BRAND.midnight,padding:20,paddingTop:12,borderBottomLeftRadius:30,borderBottomRightRadius:30},back:{width:42,height:42,borderRadius:21,backgroundColor:'#FFFFFF22',alignItems:'center',justifyContent:'center'},backText:{color:'#FFF',fontSize:32,lineHeight:34},eyebrow:{marginTop:15,color:BRAND.green,fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{marginTop:5,color:'#FFF',fontSize:29,fontWeight:'900'},subtitle:{marginTop:5,color:'#DCEBFA',fontSize:14,lineHeight:20,fontWeight:'700'},product:{margin:18,padding:16,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:BRAND.line,flexDirection:'row'},emoji:{fontSize:42,width:64},productBody:{flex:1},name:{color:BRAND.ink,fontSize:19,fontWeight:'900'},meta:{marginTop:4,color:'#477057',fontSize:11,fontWeight:'700'},price:{marginTop:7,color:BRAND.midnight,fontSize:16,fontWeight:'900'},stock:{marginTop:4,color:'#1C6337',fontSize:10,fontWeight:'800'},card:{marginHorizontal:18,padding:16,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:BRAND.line},section:{marginTop:8,marginBottom:6,color:'#52606D',fontSize:9,fontWeight:'900',letterSpacing:.8},input:{marginBottom:9,borderWidth:1,borderColor:BRAND.line,borderRadius:12,paddingHorizontal:12,paddingVertical:10,color:BRAND.ink,fontSize:13},area:{minHeight:75,textAlignVertical:'top'},location:{marginTop:2,padding:11,borderRadius:12,backgroundColor:BRAND.greenLight,alignItems:'center'},locationText:{color:'#1C6337',fontSize:10,fontWeight:'900'},summary:{margin:18,padding:16,borderRadius:20,backgroundColor:'#EAF7EE',borderWidth:1,borderColor:'#C9E5D1'},summaryTitle:{color:'#24633A',fontSize:10,fontWeight:'900',letterSpacing:1},row:{marginTop:9,flexDirection:'row',justifyContent:'space-between',color:'#3F5B48',fontSize:12},total:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:'#C9E5D1',flexDirection:'row',justifyContent:'space-between',color:BRAND.ink,fontSize:16,fontWeight:'900'},error:{marginHorizontal:18,marginBottom:10,padding:12,borderRadius:12,backgroundColor:'#FDECEC',borderWidth:1,borderColor:'#F3B5B5'},errorText:{color:'#A52222',fontSize:11,fontWeight:'800',textAlign:'center'},place:{marginHorizontal:18,minHeight:50,borderRadius:15,backgroundColor:BRAND.midnight,alignItems:'center',justifyContent:'center'},placePressed:{opacity:.75},placeText:{color:'#FFF',fontSize:11,fontWeight:'900',letterSpacing:.4},note:{margin:18,color:BRAND.muted,fontSize:11,lineHeight:17,textAlign:'center'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:30}});