import {BRAND}from'@/lib/brand';
import {getMyCustomerHomeKitchenOrders}from'@/services/homeKitchenService';
import {useRouter}from'expo-router';
import React,{useEffect,useState}from'react';
import{SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
export default function HomeKitchenOrders(){
 const router=useRouter();const[orders,setOrders]=useState<any[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{setOrders(await getMyCustomerHomeKitchenOrders())}catch(e){console.log(e)}finally{setLoading(false)}})()},[]);
 return <SafeAreaView style={s.c}><ScrollView contentContainerStyle={s.content}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹ BACK</Text></TouchableOpacity><Text style={s.eye}>CHALEGA COMMUNITY</Text><Text style={s.title}>MY FOOD ORDERS</Text><Text style={s.sub}>Orders from neighbourhood Home Kitchens.</Text>{loading?<Text style={s.muted}>Loading...</Text>:orders.length===0?<View style={s.empty}><Text style={s.emoji}>🍲</Text><Text style={s.emptyTitle}>No Home Kitchen orders yet.</Text><TouchableOpacity style={s.primary} onPress={()=>router.push('/home-kitchens')}><Text style={s.white}>DISCOVER HOME KITCHENS</Text></TouchableOpacity></View>:orders.map(o=><View style={s.card} key={o.order_id}><Text style={s.id}>#{o.order_id}</Text><Text style={s.total}>₹{Number(o.total).toLocaleString('en-IN')}</Text><Text style={s.meta}>{o.quantity} item{o.quantity===1?'':'s'} · {o.delivery_area||'Kolkata'} · COD</Text><Text style={s.status}>{o.status.replaceAll('_',' ').toUpperCase()}</Text></View>)}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:BRAND.cream},content:{padding:20,paddingBottom:60},back:{color:BRAND.teal,fontWeight:'900',marginBottom:25},eye:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:BRAND.teal},title:{fontSize:29,fontWeight:'900',color:BRAND.midnight,marginTop:5},sub:{fontSize:12,lineHeight:18,color:BRAND.muted,marginTop:6,marginBottom:20},card:{backgroundColor:'#FFF',borderRadius:18,padding:15,marginBottom:10,borderWidth:1,borderColor:BRAND.line},id:{fontSize:12,fontWeight:'900',color:BRAND.midnight},total:{marginTop:4,fontSize:20,fontWeight:'900',color:BRAND.teal},meta:{marginTop:4,fontSize:10,color:BRAND.muted},status:{marginTop:8,alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:5,borderRadius:8,backgroundColor:'#EAF7EE',color:'#1C6337',fontSize:8,fontWeight:'900'},empty:{marginTop:40,padding:25,borderRadius:20,backgroundColor:'#FFF',alignItems:'center'},emoji:{fontSize:45},emptyTitle:{marginTop:10,color:BRAND.ink,fontSize:18,fontWeight:'900'},primary:{marginTop:16,minHeight:46,paddingHorizontal:16,borderRadius:14,backgroundColor:BRAND.midnight,alignItems:'center',justifyContent:'center'},white:{color:'#FFF',fontSize:10,fontWeight:'900'},muted:{color:BRAND.muted}});
const_dummy=0;
