import {BRAND} from '@/lib/brand';
import {getApprovedKitchens,getMyHomeKitchen,HomeKitchen} from '@/services/homeKitchenService';
import {useRouter} from 'expo-router';
import React,{useCallback,useEffect,useState}from'react';
import{ActivityIndicator,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';

export default function HomeKitchens(){
 const router=useRouter();const[kitchens,setKitchens]=useState<HomeKitchen[]>([]);const[loading,setLoading]=useState(true);const[my,setMy]=useState<HomeKitchen|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([getApprovedKitchens(),getMyHomeKitchen()]);setKitchens(a);setMy(b)}catch(e){console.log('Home Kitchens load',e)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 return <SafeAreaView style={s.c}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.content}>
  <View style={s.hero}><TouchableOpacity style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></TouchableOpacity><Text style={s.eye}>CHALEGA COMMUNITY</Text><Text style={s.title}>HOME KITCHENS</Text><Text style={s.sub}>Real food. Real people. From kitchens in your neighbourhood.</Text><View style={s.heroBox}><Text style={s.heroBoxTitle}>👩‍🍳 COOK · SELL · EARN</Text><Text style={s.heroBoxText}>Turn your cooking skills into a trusted neighbourhood business.</Text></View></View>
  <View style={s.trust}><Text style={s.trustTitle}>🛡️ VERIFIED COMMUNITY FOOD</Text><Text style={s.trustText}>Kitchens are reviewed before they can accept orders. FSSAI status is part of seller verification.</Text></View>
  <TouchableOpacity style={s.sell} onPress={()=>router.push('/home-kitchen-sell')}><Text style={s.sellEye}>{my?'MY HOME KITCHEN':'WANT TO SELL YOUR FOOD?'}</Text><Text style={s.sellTitle}>{my?my.kitchen_name:'Start a Home Kitchen →'}</Text><Text style={s.sellText}>{my?my.status.toUpperCase()+' · FSSAI '+my.fssai_status.toUpperCase():'Cook from home. Start small. Let your community become your first customers.'}</Text></TouchableOpacity>
  <TouchableOpacity style={{marginHorizontal:18,marginTop:12,padding:13,borderRadius:16,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:BRAND.line}} onPress={()=>router.push('/home-kitchen-orders')}><Text style={{color:BRAND.teal,fontSize:10,fontWeight:'900'}}>📦 MY HOME FOOD ORDERS →</Text></TouchableOpacity>
  <Text style={s.section}>HOME KITCHENS NEAR YOU</Text>
  {loading?<View style={s.loading}><ActivityIndicator color={BRAND.teal}/><Text style={s.muted}>Finding local kitchens...</Text></View>:kitchens.length===0?<View style={s.empty}><Text style={s.emptyEmoji}>🍲</Text><Text style={s.emptyTitle}>The neighbourhood table is waiting.</Text><Text style={s.emptyText}>Verified home kitchens will appear here as residents join.</Text><TouchableOpacity style={s.primary} onPress={()=>router.push('/home-kitchen-sell')}><Text style={s.primaryText}>BECOME A HOME KITCHEN</Text></TouchableOpacity></View>:kitchens.map(k=><TouchableOpacity key={k.id} style={s.card} onPress={()=>router.push({pathname:'/home-kitchen',params:{kitchenId:k.id}})}><View style={s.icon}><Text style={s.iconText}>👩‍🍳</Text></View><View style={s.body}><Text style={s.badge}>{k.women_led?'👩 WOMEN-LED · ':''}🟢 VERIFIED</Text><Text style={s.name}>{k.kitchen_name}</Text><Text style={s.meta}>{k.locality||'Kolkata'} · {k.cuisine_types?.slice(0,3).join(' · ')||'Home Food'}</Text><Text style={s.story}>{k.bio||'Home-cooked food made fresh for the community.'}</Text><Text style={s.arrow}>VIEW MENU →</Text></View></TouchableOpacity>)}
  <View style={s.footer}><Text style={s.footerTitle}>FROM OUR HOMES TO OUR COMMUNITY.</Text><Text style={s.footerText}>CHALEGA is building a neighbourhood economy where residents can grow, cook, sell, deliver and earn.</Text></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:BRAND.cream},content:{paddingBottom:70},hero:{backgroundColor:BRAND.midnight,padding:20,paddingTop:12,borderBottomLeftRadius:30,borderBottomRightRadius:30},back:{width:42,height:42,borderRadius:21,backgroundColor:'#FFFFFF22',alignItems:'center',justifyContent:'center'},backText:{color:'#FFF',fontSize:32,lineHeight:34},eye:{marginTop:15,color:BRAND.green,fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{marginTop:5,color:'#FFF',fontSize:32,fontWeight:'900'},sub:{marginTop:5,color:'#DCEBFA',fontSize:15,lineHeight:21,fontWeight:'700'},heroBox:{marginTop:17,padding:14,borderRadius:18,backgroundColor:'#FFFFFF12'},heroBoxTitle:{color:BRAND.green,fontSize:11,fontWeight:'900',letterSpacing:.6},heroBoxText:{marginTop:5,color:'#DCEBFA',fontSize:12,lineHeight:18},trust:{margin:18,padding:15,borderRadius:19,backgroundColor:'#EAF7EE',borderWidth:1,borderColor:'#C9E5D1'},trustTitle:{color:'#175A2D',fontSize:11,fontWeight:'900'},trustText:{marginTop:5,color:'#4C6B57',fontSize:11,lineHeight:17},sell:{marginHorizontal:18,padding:16,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:BRAND.line},sellEye:{color:'#24633A',fontSize:9,fontWeight:'900',letterSpacing:.8},sellTitle:{marginTop:4,color:BRAND.ink,fontSize:19,fontWeight:'900'},sellText:{marginTop:4,color:BRAND.muted,fontSize:11,lineHeight:17},section:{marginHorizontal:18,marginTop:22,marginBottom:10,color:BRAND.ink,fontSize:20,fontWeight:'900'},loading:{padding:30,alignItems:'center'},muted:{marginTop:8,color:BRAND.muted},card:{marginHorizontal:18,marginBottom:12,padding:14,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:BRAND.line,flexDirection:'row'},icon:{width:72,height:72,borderRadius:19,backgroundColor:'#F3EEE7',alignItems:'center',justifyContent:'center',marginRight:12},iconText:{fontSize:36},body:{flex:1},badge:{color:'#1B6A37',fontSize:8,fontWeight:'900',letterSpacing:.4},name:{marginTop:4,color:BRAND.ink,fontSize:17,fontWeight:'900'},meta:{marginTop:4,color:'#477057',fontSize:10,fontWeight:'800'},story:{marginTop:5,color:BRAND.muted,fontSize:11,lineHeight:16},arrow:{marginTop:8,color:BRAND.midnight,fontSize:9,fontWeight:'900'},empty:{marginHorizontal:18,padding:28,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:BRAND.line,alignItems:'center'},emptyEmoji:{fontSize:44},emptyTitle:{marginTop:9,color:BRAND.ink,fontSize:18,fontWeight:'900',textAlign:'center'},emptyText:{marginTop:6,color:BRAND.muted,fontSize:12,lineHeight:18,textAlign:'center'},primary:{marginTop:16,paddingHorizontal:16,minHeight:46,borderRadius:14,backgroundColor:BRAND.midnight,alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontSize:10,fontWeight:'900'},footer:{margin:18,padding:17,borderRadius:20,backgroundColor:BRAND.midnight},footerTitle:{color:BRAND.green,fontSize:11,fontWeight:'900'},footerText:{marginTop:6,color:'#DCEBFA',fontSize:11,lineHeight:18}});
