create table if not exists public.kmc_ward_geometry_sources (
  source_id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text,
  source_type text not null,
  boundary_version text,
  status text not null default 'reference_only',
  ward_count integer,
  is_official boolean not null default false,
  is_production_candidate boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kmc_ward_geometry_sources_status_chk check (status in ('reference_only','candidate','validated','superseded','rejected'))
);
create unique index if not exists kmc_ward_geometry_sources_name_uq on public.kmc_ward_geometry_sources(source_name);

insert into public.kmc_ward_geometry_sources
  (source_name, source_url, source_type, boundary_version, status, ward_count, is_official, is_production_candidate, notes)
values
  ('KMC Ward Wise Smart Map', 'https://www.kmcgov.in/KMCPortal/jsp/WardwiseSmartMap.jsp', 'official_web_map', 'legacy_pre_2026', 'reference_only', 144, true, false, 'Official KMC ward smart-map page. Current indexed map represents the legacy ward system; do not use as 2026 209-ward production geometry.'),
  ('Kolkata Collectorate Ward Wise Map', 'https://kolkatacollectorate.wb.gov.in/map-of-district/', 'official_static_map', 'legacy_pre_2026', 'reference_only', 144, true, false, 'Official district administration map page. Published ward image is a legacy map and is reference-only for the 2026 209-ward system.'),
  ('UDMA Draft Schedule II Order 1660', 'https://udma.wb.gov.in/circular', 'official_boundary_text', 'draft_2026_08_22', 'candidate', 209, true, false, 'Official 22 Aug 2026 draft Schedule II. Contains proposed 209 ward boundary descriptions; not final GIS geometry.')
on conflict (source_name) do update set source_url=excluded.source_url, source_type=excluded.source_type, boundary_version=excluded.boundary_version, status=excluded.status, ward_count=excluded.ward_count, is_official=excluded.is_official, is_production_candidate=excluded.is_production_candidate, notes=excluded.notes, updated_at=now();;
