-- Chalega Delivery Network foundation
-- Driver profiles, delivery jobs, assignments, event history, and payouts.
-- Client roles are restricted by RLS; operational writes remain server-side.

create table if not exists public.chalega_delivery_partners (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  status text not null default 'pending'
    check (status = any (array['pending','approved','suspended','rejected'])),
  availability text not null default 'offline'
    check (availability = any (array['offline','online','busy'])),
  vehicle_type text not null
    check (vehicle_type = any (array['bike','scooter','car','bicycle','other'])),
  vehicle_number text,
  phone text,
  city_area text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chalega_delivery_jobs (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique references public.orders(order_id) on delete restrict,
  status text not null default 'pending'
    check (status = any (array[
      'pending','offered','accepted','pickup','picked_up',
      'out_for_delivery','delivered','cancelled'
    ])),
  pickup_address text,
  pickup_area text,
  pickup_pin text,
  drop_address text not null,
  drop_area text,
  drop_pin text,
  delivery_fee numeric(10,2) not null default 0 check (delivery_fee >= 0),
  partner_earnings numeric(10,2) not null default 0 check (partner_earnings >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  accepted_at timestamptz,
  picked_up_at timestamptz,
  delivered_at timestamptz
);

create table if not exists public.chalega_delivery_assignments (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.chalega_delivery_jobs(id) on delete cascade,
  partner_id uuid not null references public.chalega_delivery_partners(id) on delete cascade,
  status text not null default 'offered'
    check (status = any (array['offered','accepted','rejected','expired','cancelled'])),
  offered_at timestamptz not null default now(),
  accepted_at timestamptz,
  rejected_at timestamptz,
  unique (job_id, partner_id)
);

create table if not exists public.chalega_delivery_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.chalega_delivery_jobs(id) on delete cascade,
  partner_id uuid references public.chalega_delivery_partners(id) on delete set null,
  event_type text not null
    check (event_type = any (array[
      'job_created','job_offered','job_accepted','job_rejected',
      'pickup_started','picked_up','out_for_delivery',
      'delivery_otp_verified','delivered','cancelled'
    ])),
  metadata jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chalega_delivery_payouts (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null unique references public.chalega_delivery_jobs(id) on delete restrict,
  partner_id uuid not null references public.chalega_delivery_partners(id) on delete restrict,
  amount numeric(10,2) not null check (amount >= 0),
  status text not null default 'pending'
    check (status = any (array['pending','approved','paid','failed'])),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_delivery_jobs_status
  on public.chalega_delivery_jobs(status);
create index if not exists idx_delivery_assignments_partner
  on public.chalega_delivery_assignments(partner_id, status);
create index if not exists idx_delivery_events_job
  on public.chalega_delivery_events(job_id, created_at);
create index if not exists idx_delivery_payouts_partner
  on public.chalega_delivery_payouts(partner_id, status);

alter table public.chalega_delivery_partners enable row level security;
alter table public.chalega_delivery_jobs enable row level security;
alter table public.chalega_delivery_assignments enable row level security;
alter table public.chalega_delivery_events enable row level security;
alter table public.chalega_delivery_payouts enable row level security;

revoke all on table
  public.chalega_delivery_partners,
  public.chalega_delivery_jobs,
  public.chalega_delivery_assignments,
  public.chalega_delivery_events,
  public.chalega_delivery_payouts
from anon, authenticated;

grant select, insert on table public.chalega_delivery_partners to authenticated;
grant select on table public.chalega_delivery_jobs to authenticated;
grant select on table public.chalega_delivery_assignments to authenticated;
grant select on table public.chalega_delivery_events to authenticated;
grant select on table public.chalega_delivery_payouts to authenticated;

grant all on table
  public.chalega_delivery_partners,
  public.chalega_delivery_jobs,
  public.chalega_delivery_assignments,
  public.chalega_delivery_events,
  public.chalega_delivery_payouts
to service_role;

create policy "delivery partners read own profile"
  on public.chalega_delivery_partners
  for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "delivery partners create own application"
  on public.chalega_delivery_partners
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and status = 'pending'
    and availability = 'offline'
  );

create policy "drivers read assigned jobs"
  on public.chalega_delivery_jobs
  for select to authenticated
  using (
    exists (
      select 1
      from public.chalega_delivery_assignments a
      join public.chalega_delivery_partners p on p.id = a.partner_id
      where a.job_id = public.chalega_delivery_jobs.id
        and p.user_id = (select auth.uid())
    )
  );

create policy "drivers read own assignments"
  on public.chalega_delivery_assignments
  for select to authenticated
  using (
    exists (
      select 1
      from public.chalega_delivery_partners p
      where p.id = partner_id
        and p.user_id = (select auth.uid())
    )
  );

create policy "drivers read own delivery events"
  on public.chalega_delivery_events
  for select to authenticated
  using (
    exists (
      select 1
      from public.chalega_delivery_partners p
      where p.id = partner_id
        and p.user_id = (select auth.uid())
    )
  );

create policy "drivers read own payouts"
  on public.chalega_delivery_payouts
  for select to authenticated
  using (
    exists (
      select 1
      from public.chalega_delivery_partners p
      where p.id = partner_id
        and p.user_id = (select auth.uid())
    )
  );
