CREATE TABLE IF NOT EXISTS public.kmc_boundary_versions (
  version_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_key text NOT NULL UNIQUE,
  source_order text NOT NULL,
  source_date date,
  source_url text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','proposed','final','superseded')),
  is_current boolean NOT NULL DEFAULT false,
  effective_from timestamptz,
  effective_to timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS kmc_boundary_versions_one_current_idx ON public.kmc_boundary_versions (is_current) WHERE is_current = true;
INSERT INTO public.kmc_boundary_versions (version_key, source_order, source_date, source_url, status, is_current, notes)
VALUES ('draft_2026_08_22','1660/UDMA-15011(99)/53/2026-LS-MA SEC','2026-08-22','https://udma.wb.gov.in/circular','draft',true,'Draft Schedule II of the Kolkata Municipal Corporation Act, 1980. Not for production ward assignment until official final boundary/GIS publication and validation.')
ON CONFLICT (version_key) DO UPDATE SET source_order=EXCLUDED.source_order, source_date=EXCLUDED.source_date, source_url=EXCLUDED.source_url, status=EXCLUDED.status, is_current=EXCLUDED.is_current, notes=EXCLUDED.notes, updated_at=now();;
