create table if not exists public.daily_health_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  checkin_date date not null,
  mood text not null,
  water integer not null default 0,
  activity text not null,
  sleep text not null,
  health_score integer,
  steps integer not null default 0,
  goal integer not null default 4000,
  streak integer not null default 0,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint daily_health_checkins_unique_user_date
    unique (user_id, checkin_date),

  constraint daily_health_checkins_water_check
    check (water >= 0),

  constraint daily_health_checkins_steps_check
    check (steps >= 0),

  constraint daily_health_checkins_goal_check
    check (goal > 0),

  constraint daily_health_checkins_streak_check
    check (streak >= 0),

  constraint daily_health_checkins_health_score_check
    check (health_score is null or (health_score >= 0 and health_score <= 100))
);

alter table public.daily_health_checkins enable row level security;

drop policy if exists "Users can view own health checkins"
on public.daily_health_checkins;

create policy "Users can view own health checkins"
on public.daily_health_checkins
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own health checkins"
on public.daily_health_checkins;

create policy "Users can insert own health checkins"
on public.daily_health_checkins
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own health checkins"
on public.daily_health_checkins;

create policy "Users can update own health checkins"
on public.daily_health_checkins
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists daily_health_checkins_user_date_idx
on public.daily_health_checkins (user_id, checkin_date desc);